[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
check_tool = clangtidy
check_flags =
    clangtidy: --extra-arg=-Wno-unknown-warning-option

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    mathieucarbou/ESPAsyncWebServer @ ^3.1.5
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0
    robtillaart/INA226 @ ^0.6.0
    knolleary/PubSubClient @ ^2.8
